version: "3"
services:

  api:
    build: .
    image: event-planner-api:latest
    depends_on:
      - database
    ports:
      - "8082:8080"
    env_file:
      - .env
  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data: